name: client
description: A client for the challenge Eldorado.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.7
  http: ^1.4.0
  very_good_analysis: ^9.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
