name: challenge_eldorado
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  client:
    path: ./repositories/client
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  i18n:
    path: ./repositories/i18n
  recommendation_repository:
    path: ./repositories/recommendation_repository
  shimmer: ^3.0.0
  ui:
    path: ./repositories/ui
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cripto_currencies/
    - assets/fiat_currencies/