name: ui
description: A UI library for the challenge Eldorado.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  client:
    path: ../client
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  i18n:
    path: ../i18n

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
