name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Get dependencies for local packages
      run: |
        cd repositories/client && flutter pub get
        cd ../i18n && flutter pub get
        cd ../ui && flutter pub get
        cd ../recommendation_repository && flutter pub get

    - name: Test local packages
      run: |
        cd repositories/client && flutter test
        cd ../recommendation_repository && flutter test
        cd ../ui && flutter test

    - name: Analyze code
      run: flutter analyze

    - name: Build web app
      run: flutter build web --base-href "/coding-interview-frontend/"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: build/web/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4